In [1]:
import numpy as np

In [9]:
#initialising an array
a=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(a)
a=np.arange(1,10,2) # like range function
print(a)
#a=np.arange(1,10,2,dtype=int8) -> dtype to specify the datatype and size
a=np.linspace(1,3,6) #similar to range but (start,stop,no of items)
print(a)
a=np.fromstring("1 2 3",dtype=np.int, sep=" ")
print(a)
a=np.zeros((2,2)) # matrix of zeros -> (columns,rows)
print(a)
a=np.ones((2,2)) # matrix of ones -> (columns,rows)
print(a)
a=np.full((2,2),10) # matrix of x -> (columns,rows),x
print(a)
b=np.zeros_like(a) # zero matrix with dimensions of a
print(b)

[[1 2 3 4 5]
 [1 2 3 4 5]]
[1 3 5 7 9]
[1.  1.4 1.8 2.2 2.6 3. ]
[1 2 3]
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[10 10]
 [10 10]]
[[0 0]
 [0 0]]


<ipython-input-9-87ba8c32cb87>:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.fromstring("1 2 3",dtype=np.int, sep=" ")


In [11]:
print(a.size)
print(a.shape) #dimensions
print(a.ndim) #no of dimensions
print(a.itemsize) # size of element
print(a.dtype) #datatype
print(a.nbytes) # size of entire array

4
(2, 2)
2
4
int32
16


In [15]:
#list functions
print(a[1])
print(a[1][1])
print(a[0:1]) #slicing
print(a[:,0:1]) #2d slicing

[10 10]
10
[[10 10]]
[[10]
 [10]]


a=np.array([[1,3,5,7,9,11],[1,2,3,4,5,6],[7,8,9,10,11,12]])

print(a>4)
print(a*10)

print(a.min())
print(a.sum())
print(a.mean())
print(a.var())
print(a.std())
print(a.argmax()) #returns the index of max element
print(a.argmin()) #returns the index of min element
print(a.argsort()) #array of indices for sorted array

In [27]:
print(a[:,2:3]) # to get column 2
print()
c = a[:,2:3] # pointer to original column in a, changes to c reflect in array
c*=10 # values in 2nd column of array multiplied by 10
print(a)
print()
c+=3
print(a)

[[5033]
 [3033]
 [9033]]

[[    1     3 50330     7     9    11]
 [    1     2 30330     4     5     6]
 [    7     8 90330    10    11    12]]

[[    1     3 50333     7     9    11]
 [    1     2 30333     4     5     6]
 [    7     8 90333    10    11    12]]


In [28]:
#numpy random functions
r=np.random.random(6)
print(r)
r=np.random.randint(6,100,4) #lower and inclusive upper limit, size
print(r)
print(np.random.choice(r))
np.random.shuffle(r)
print(r)
r.sort()
print(r)

[0.24010161 0.89867266 0.83163758 0.01376242 0.74396202 0.30642202]
[17 45 66 54]
66
[54 66 17 45]
[17 45 54 66]


In [ ]:
#Reshape, Swap Axes, Flatten
c = np.arange(-9, -3,).reshape(2,3)
print(c)

c = c.swapaxes(0,1)
print(c)

c = c.flatten()
print(c)

In [ ]:
#UpCasting, Rounding, Print Formatting
e = np.array([(1.566666,2,3), (4,5,6)])
print(e.dtype)

e = e.round(4)
print(e)

np.set_printoptions(precision=2, suppress=True)    # show 2 decimal places, suppress scientific notation
print(e)